{
    "checksum": "3f852c5fcd3ce445fb57e407404bce734b2cf2a064c1a5c1a16f5d390010df05",
    "file": "exception.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 4,
    "package": "backblaze-b2",
    "path": "backblaze-b2/1.3.8-5/b2/account_info/exception.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/backblaze-b2/1.3.8-5/",
        "metric": {
            "size": 1288
        },
        "pts_link": "https://tracker.debian.org/pkg/backblaze-b2",
        "sloc": [
            [
                "python",
                10230
            ],
            [
                "sh",
                149
            ],
            [
                "makefile",
                40
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/backblaze-b2",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/b/backblaze-b2/1.3.8-5/b2/account_info/exception.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1011,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.3.8-5"
}