{
    "checksum": "a8e9bd4d34d5c63d4fc0085da915e0dd6c51a6ee17a82ac60ab9f57e30e2a9a4",
    "file": "autokey-status-error.svg",
    "mime": {
        "encoding": "us-ascii",
        "type": "image/svg+xml"
    },
    "number_of_duplicates": 4,
    "package": "autokey",
    "path": "autokey/0.95.10-2/config/Humanity/autokey-status-error.svg",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/autokey/0.95.10-2/",
        "metric": {
            "size": 2092
        },
        "pts_link": "https://tracker.debian.org/pkg/autokey",
        "sloc": [
            [
                "python",
                9372
            ],
            [
                "xml",
                2741
            ],
            [
                "javascript",
                249
            ],
            [
                "sh",
                24
            ],
            [
                "makefile",
                4
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/autokey",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/autokey/0.95.10-2/config/Humanity/autokey-status-error.svg",
    "stat": {
        "perms": "rw-r--r--",
        "size": 2680,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.95.10-2"
}