{
    "checksum": "e39acfd0f39ee03e2cda4a908acfbc8c6216cfc4fbc4a62967b1f6b3b898f643",
    "file": "tools.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "backintime",
    "path": "backintime/1.2.1-3/.pc/00-fix-946349.patch/common/tools.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/backintime/1.2.1-3/",
        "metric": {
            "size": 3628
        },
        "pts_link": "https://tracker.debian.org/pkg/backintime",
        "sloc": [
            [
                "python",
                15767
            ],
            [
                "sh",
                525
            ],
            [
                "makefile",
                171
            ],
            [
                "xml",
                72
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/jmw/pkg-backintime",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/b/backintime/1.2.1-3/.pc/00-fix-946349.patch/common/tools.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 72795,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.2.1-3"
}