{
    "checksum": "ee07bea3f00e3cdb04be303fad9b8051cf47fc13904b79c5d8c3821993d65928",
    "file": "error.pyx",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "azure-uamqp-python",
    "path": "azure-uamqp-python/1.4.1-1/src/error.pyx",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-uamqp-python/1.4.1-1/",
        "metric": {
            "size": 35160
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-uamqp-python",
        "sloc": [
            [
                "ansic",
                181532
            ],
            [
                "cpp",
                7738
            ],
            [
                "python",
                7485
            ],
            [
                "cs",
                5766
            ],
            [
                "sh",
                718
            ],
            [
                "xml",
                298
            ],
            [
                "makefile",
                34
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-uamqp-python",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-uamqp-python/1.4.1-1/src/error.pyx",
    "stat": {
        "perms": "rw-r--r--",
        "size": 3007,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.4.1-1"
}