{
    "checksum": "4b54fe14ebf01f722210af6b9118d732bdb7f549a9f555b15743e18ee053d786",
    "file": "conversion_error_ui.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 3,
    "package": "calibre",
    "path": "calibre/5.27.0+dfsg-1/src/calibre/gui2/dialogs/conversion_error_ui.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/calibre/5.27.0+dfsg-1/",
        "metric": {
            "size": 392284
        },
        "pts_link": "https://tracker.debian.org/pkg/calibre",
        "sloc": [
            [
                "python",
                405574
            ],
            [
                "ansic",
                79654
            ],
            [
                "javascript",
                58060
            ],
            [
                "cpp",
                16524
            ],
            [
                "xml",
                1752
            ],
            [
                "sh",
                841
            ],
            [
                "sql",
                629
            ],
            [
                "objc",
                456
            ],
            [
                "makefile",
                55
            ],
            [
                "sed",
                3
            ]
        ],
        "suites": [
            "sid"
        ],
        "vcs_browser": "https://github.com/debian-calibre/calibre",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/c/calibre/5.27.0%2Bdfsg-1/src/calibre/gui2/dialogs/conversion_error_ui.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 2111,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "5.27.0+dfsg-1"
}