{
    "checksum": "98950e9041e216a1205426fd2309de66ec0836bd94b77cc9d9ae3407e729282b",
    "file": "utils.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "aiomysql",
    "path": "aiomysql/0.0.20-2/.pc/0001-Run-tests-for-python-3.7-in-CI-and-fix-failing-tests.patch/aiomysql/utils.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/aiomysql/0.0.20-2/",
        "metric": {
            "size": 868
        },
        "pts_link": "https://tracker.debian.org/pkg/aiomysql",
        "sloc": [
            [
                "python",
                6713
            ],
            [
                "makefile",
                202
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/modules/aiomysql",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/aiomysql/0.0.20-2/.pc/0001-Run-tests-for-python-3.7-in-CI-and-fix-failing-tests.patch/aiomysql/utils.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 3590,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.0.20-2"
}