{
    "checksum": "4ac4343dba0a7149a8538f19e12974e6cba1e95a39b84ddb25787365a3bb22d3",
    "file": "test_table_encryption.test_invalid_encryption_operations_fail_batch.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 1,
    "package": "azure-cosmos-table-python",
    "path": "azure-cosmos-table-python/1.0.5+git20191025-5/azure-cosmosdb-table/tests/recordings/test_table_encryption.test_invalid_encryption_operations_fail_batch.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-cosmos-table-python/1.0.5+git20191025-5/",
        "metric": {
            "size": 6140
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-cosmos-table-python",
        "sloc": [
            [
                "python",
                8856
            ],
            [
                "makefile",
                265
            ],
            [
                "sh",
                7
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/modules/azure-cosmos-table-python",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-cosmos-table-python/1.0.5%2Bgit20191025-5/azure-cosmosdb-table/tests/recordings/test_table_encryption.test_invalid_encryption_operations_fail_batch.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 2684,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.0.5+git20191025-5"
}